CREATE TABLE default_role_snapshots (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),

    role_api_label text NOT NULL,

    platform_version text NOT NULL,

    definition jsonb NOT NULL,

    definition_sha256 text NOT NULL,

    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    created_by uuid,
    updated_by uuid,
    deleted_at timestamptz,

    is_active boolean NOT NULL DEFAULT true,
    is_deleted boolean NOT NULL DEFAULT false,

    CONSTRAINT default_role_snapshots_unique
        UNIQUE (
            role_api_label,
            platform_version
        )
);

CREATE INDEX idx_default_role_snapshots_active_version
ON default_role_snapshots(platform_version, role_api_label)
WHERE is_active = true AND is_deleted = false;

INSERT INTO default_role_snapshots (id, role_api_label, platform_version, definition, definition_sha256)
VALUES
  (gen_random_uuid(), 'primary_admin', 'v1', '{"api_label":"primary_admin","assignable":false,"category":"administration","description":"Protected tenant owner-administrator role created during tenant provisioning.","display_name":"Primary Admin","metadata":{"immutable_api_label":true,"purpose":"tenant_owner","risk_level":"critical","scope":"tenant","system":true,"template_version":"v1","transfer_required":true},"permission_labels":["tenant.read","tenant.update","user.read","user.create","user.update","user.disable","user.block","user.delete","user.invite","role.read","role.create","role.update","role.delete","role.assign","permission.read","user_pool.read","user_pool.create","user_pool.update","user_pool.delete","auth_policy.read","auth_policy.update","password_policy.read","password_policy.update","recovery_policy.read","recovery_policy.update","login_policy.read","login_policy.update","session.read","session.revoke","device.read","device.revoke","mfa.read","mfa.reset","totp.read","totp.reset","webauthn.read","webauthn.revoke","application.read","application.create","application.update","application.disable","application.delete","application.secret.rotate","oauth.read","oauth.revoke","oidc.read","oidc.update","saml.read","saml.update","email.read","email.update","sms.read","sms.update","notification.read","notification.update","webhook.read","webhook.update","webhook.replay","post_auth_hook.read","post_auth_hook.create","post_auth_hook.update","post_auth_hook.delete","key.read","key.rotate","realtime.read","realtime.update","profile_field.read","profile_field.create","profile_field.update","profile_field.delete","audit.read","support.read","support.send"],"protected_from_delete":true}'::jsonb, '1fb1a1fd4b4bde55454cf6a35a6b16a18a37d1d2b2dbb81315d74c0609b6fe83'),
  (gen_random_uuid(), 'tenant_admin', 'v1', '{"api_label":"tenant_admin","assignable":true,"category":"administration","description":"Broad tenant administration without ownership-only cryptographic key rotation privileges.","display_name":"Tenant Admin","metadata":{"immutable_api_label":true,"purpose":"tenant_administration","risk_level":"high","scope":"tenant","system":true,"template_version":"v1"},"permission_labels":["tenant.read","tenant.update","user.read","user.create","user.update","user.disable","user.block","user.delete","user.invite","role.read","role.create","role.update","role.delete","role.assign","permission.read","user_pool.read","user_pool.create","user_pool.update","user_pool.delete","auth_policy.read","auth_policy.update","password_policy.read","password_policy.update","recovery_policy.read","recovery_policy.update","login_policy.read","login_policy.update","session.read","session.revoke","device.read","device.revoke","mfa.read","mfa.reset","totp.read","totp.reset","webauthn.read","webauthn.revoke","application.read","application.create","application.update","application.disable","application.delete","oauth.read","oauth.revoke","oidc.read","oidc.update","saml.read","saml.update","email.read","email.update","sms.read","sms.update","notification.read","notification.update","webhook.read","webhook.update","webhook.replay","post_auth_hook.read","post_auth_hook.create","post_auth_hook.update","post_auth_hook.delete","key.read","realtime.read","realtime.update","profile_field.read","profile_field.create","profile_field.update","profile_field.delete","audit.read","support.read","support.send"],"protected_from_delete":true}'::jsonb, '2d67fab23f7c01ad09ce8c0564a43dfd762d98495f3b1b56b1876bb78e592839'),
  (gen_random_uuid(), 'user_manager', 'v1', '{"api_label":"user_manager","assignable":true,"category":"identity","description":"Manages tenant users, authentication recovery, sessions, devices, and MFA support operations.","display_name":"User Manager","metadata":{"immutable_api_label":true,"purpose":"identity_administration","risk_level":"high","scope":"tenant","system":true,"template_version":"v1"},"permission_labels":["user.read","user.create","user.update","user.disable","user.block","user.delete","user.invite","session.read","session.revoke","device.read","device.revoke","mfa.read","mfa.reset","totp.read","totp.reset","webauthn.read","webauthn.revoke","recovery_policy.read","profile_field.read","support.read"],"protected_from_delete":true}'::jsonb, 'f7c864e6c95894e139f5cbc48fbfe41ac6f804a7d948fd48b87f18d4e8b69735'),
  (gen_random_uuid(), 'application_manager', 'v1', '{"api_label":"application_manager","assignable":true,"category":"application","description":"Manages tenant applications, federation protocols, hooks, webhooks, and realtime integration settings.","display_name":"Application Manager","metadata":{"immutable_api_label":true,"purpose":"application_administration","risk_level":"high","scope":"tenant","system":true,"template_version":"v1"},"permission_labels":["application.read","application.create","application.update","application.disable","application.delete","application.secret.rotate","oauth.read","oauth.revoke","oidc.read","oidc.update","saml.read","saml.update","webhook.read","webhook.update","webhook.replay","post_auth_hook.read","post_auth_hook.create","post_auth_hook.update","post_auth_hook.delete","realtime.read","realtime.update"],"protected_from_delete":true}'::jsonb, 'e3a32a086367131b930de9dbb9aecaa851bf47606ab5425a0b62fb409e8d3b5f'),
  (gen_random_uuid(), 'security_viewer', 'v1', '{"api_label":"security_viewer","assignable":true,"category":"security","description":"Read-only security, identity-policy, federation, session, device, key-metadata, and audit visibility.","display_name":"Security Viewer","metadata":{"immutable_api_label":true,"purpose":"security_observation","read_only":true,"risk_level":"medium","scope":"tenant","system":true,"template_version":"v1"},"permission_labels":["tenant.read","user.read","role.read","permission.read","user_pool.read","auth_policy.read","password_policy.read","recovery_policy.read","login_policy.read","session.read","device.read","mfa.read","totp.read","webauthn.read","application.read","oauth.read","oidc.read","saml.read","webhook.read","post_auth_hook.read","key.read","realtime.read","audit.read"],"protected_from_delete":true}'::jsonb, '74f1d978727c639d2cf3e907a07a8c80a1f8994ac1f4db738e5204b1e193a499'),
  (gen_random_uuid(), 'support_agent', 'v1', '{"api_label":"support_agent","assignable":true,"category":"support","description":"Supports tenant users with bounded session, device, and MFA recovery actions.","display_name":"Support Agent","metadata":{"immutable_api_label":true,"purpose":"user_support","risk_level":"high","scope":"tenant","system":true,"template_version":"v1"},"permission_labels":["user.read","session.read","session.revoke","device.read","device.revoke","mfa.read","mfa.reset","totp.read","totp.reset","webauthn.read","webauthn.revoke","recovery_policy.read","support.read","support.send"],"protected_from_delete":true}'::jsonb, '8e251596385888ac6607101400d2c2931c9f84dfb29d881c18fde723f6176273'),
  (gen_random_uuid(), 'viewer', 'v1', '{"api_label":"viewer","assignable":true,"category":"read_only","description":"General read-only tenant administration visibility without cryptographic key metadata.","display_name":"Viewer","metadata":{"immutable_api_label":true,"purpose":"read_only_administration","read_only":true,"risk_level":"low","scope":"tenant","system":true,"template_version":"v1"},"permission_labels":["tenant.read","user.read","role.read","permission.read","user_pool.read","auth_policy.read","password_policy.read","recovery_policy.read","login_policy.read","session.read","device.read","mfa.read","totp.read","webauthn.read","application.read","oauth.read","oidc.read","saml.read","email.read","sms.read","notification.read","webhook.read","post_auth_hook.read","realtime.read","profile_field.read","audit.read","support.read"],"protected_from_delete":true}'::jsonb, 'db79676afe3a5ea8d821f41e0c654445715e9cb104a163130d7c9a54dd0297ee'),
  (gen_random_uuid(), 'standard_user', 'v1', '{"api_label":"standard_user","assignable":true,"category":"self_service","description":"Self-service role for a normal tenant user.","display_name":"Standard User","metadata":{"immutable_api_label":true,"purpose":"end_user_self_service","risk_level":"low","scope":"self","system":true,"template_version":"v1"},"permission_labels":["self.profile.read","self.profile.update","self.session.read","self.session.revoke","self.device.read","self.device.revoke","self.mfa.manage"],"protected_from_delete":true}'::jsonb, '7cefd451d761d167ebb3630e8877430e692cff8fffdb969614db50b65ec574ad')
ON CONFLICT (role_api_label, platform_version) DO NOTHING;
