package constants

type DefaultRole struct {
	APILabel            string         `json:"api_label"`
	DisplayName         string         `json:"display_name"`
	Description         string         `json:"description"`
	Category            string         `json:"category"`
	Assignable          bool           `json:"assignable"`
	ProtectedFromDelete bool           `json:"protected_from_delete"`
	PermissionLabels    []string       `json:"permission_labels"`
	Metadata            map[string]any `json:"metadata"`
}

const DefaultRoleTemplateVersion = "v1"

var DefaultRoles = []DefaultRole{
	{
		APILabel:            "primary_admin",
		DisplayName:         "Primary Admin",
		Description:         "Protected tenant owner-administrator role created during tenant provisioning.",
		Category:            "administration",
		Assignable:          false,
		ProtectedFromDelete: true,
		PermissionLabels: []string{
			"tenant.read",
			"tenant.update",
			"user.read",
			"user.create",
			"user.update",
			"user.disable",
			"user.block",
			"user.delete",
			"user.invite",
			"role.read",
			"role.create",
			"role.update",
			"role.delete",
			"role.assign",
			"permission.read",
			"user_pool.read",
			"user_pool.create",
			"user_pool.update",
			"user_pool.delete",
			"auth_policy.read",
			"auth_policy.update",
			"password_policy.read",
			"password_policy.update",
			"recovery_policy.read",
			"recovery_policy.update",
			"login_policy.read",
			"login_policy.update",
			"session.read",
			"session.revoke",
			"device.read",
			"device.revoke",
			"mfa.read",
			"mfa.reset",
			"totp.read",
			"totp.reset",
			"webauthn.read",
			"webauthn.revoke",
			"application.read",
			"application.create",
			"application.update",
			"application.disable",
			"application.delete",
			"application.secret.rotate",
			"oauth.read",
			"oauth.revoke",
			"oidc.read",
			"oidc.update",
			"saml.read",
			"saml.update",
			"email.read",
			"email.update",
			"sms.read",
			"sms.update",
			"notification.read",
			"notification.update",
			"webhook.read",
			"webhook.update",
			"webhook.replay",
			"post_auth_hook.read",
			"post_auth_hook.create",
			"post_auth_hook.update",
			"post_auth_hook.delete",
			"key.read",
			"key.rotate",
			"realtime.read",
			"realtime.update",
			"profile_field.read",
			"profile_field.create",
			"profile_field.update",
			"profile_field.delete",
			"audit.read",
			"support.read",
			"support.send",
		},
		Metadata: map[string]any{
			"system":              true,
			"scope":               "tenant",
			"purpose":             "tenant_owner",
			"risk_level":          "critical",
			"immutable_api_label": true,
			"transfer_required":   true,
		},
	},
	{
		APILabel:            "tenant_admin",
		DisplayName:         "Tenant Admin",
		Description:         "Broad tenant administration without ownership-only cryptographic key rotation privileges.",
		Category:            "administration",
		Assignable:          true,
		ProtectedFromDelete: true,
		PermissionLabels: []string{
			"tenant.read",
			"tenant.update",
			"user.read",
			"user.create",
			"user.update",
			"user.disable",
			"user.block",
			"user.delete",
			"user.invite",
			"role.read",
			"role.create",
			"role.update",
			"role.delete",
			"role.assign",
			"permission.read",
			"user_pool.read",
			"user_pool.create",
			"user_pool.update",
			"user_pool.delete",
			"auth_policy.read",
			"auth_policy.update",
			"password_policy.read",
			"password_policy.update",
			"recovery_policy.read",
			"recovery_policy.update",
			"login_policy.read",
			"login_policy.update",
			"session.read",
			"session.revoke",
			"device.read",
			"device.revoke",
			"mfa.read",
			"mfa.reset",
			"totp.read",
			"totp.reset",
			"webauthn.read",
			"webauthn.revoke",
			"application.read",
			"application.create",
			"application.update",
			"application.disable",
			"application.delete",
			"oauth.read",
			"oauth.revoke",
			"oidc.read",
			"oidc.update",
			"saml.read",
			"saml.update",
			"email.read",
			"email.update",
			"sms.read",
			"sms.update",
			"notification.read",
			"notification.update",
			"webhook.read",
			"webhook.update",
			"webhook.replay",
			"post_auth_hook.read",
			"post_auth_hook.create",
			"post_auth_hook.update",
			"post_auth_hook.delete",
			"key.read",
			"realtime.read",
			"realtime.update",
			"profile_field.read",
			"profile_field.create",
			"profile_field.update",
			"profile_field.delete",
			"audit.read",
			"support.read",
			"support.send",
		},
		Metadata: map[string]any{
			"system":              true,
			"scope":               "tenant",
			"purpose":             "tenant_administration",
			"risk_level":          "high",
			"immutable_api_label": true,
		},
	},
	{
		APILabel:            "user_manager",
		DisplayName:         "User Manager",
		Description:         "Manages tenant users, authentication recovery, sessions, devices, and MFA support operations.",
		Category:            "identity",
		Assignable:          true,
		ProtectedFromDelete: true,
		PermissionLabels: []string{
			"user.read",
			"user.create",
			"user.update",
			"user.disable",
			"user.block",
			"user.delete",
			"user.invite",
			"session.read",
			"session.revoke",
			"device.read",
			"device.revoke",
			"mfa.read",
			"mfa.reset",
			"totp.read",
			"totp.reset",
			"webauthn.read",
			"webauthn.revoke",
			"recovery_policy.read",
			"profile_field.read",
			"support.read",
		},
		Metadata: map[string]any{
			"system":              true,
			"scope":               "tenant",
			"purpose":             "identity_administration",
			"risk_level":          "high",
			"immutable_api_label": true,
		},
	},
	{
		APILabel:            "application_manager",
		DisplayName:         "Application Manager",
		Description:         "Manages tenant applications, federation protocols, hooks, webhooks, and realtime integration settings.",
		Category:            "application",
		Assignable:          true,
		ProtectedFromDelete: true,
		PermissionLabels: []string{
			"application.read",
			"application.create",
			"application.update",
			"application.disable",
			"application.delete",
			"application.secret.rotate",
			"oauth.read",
			"oauth.revoke",
			"oidc.read",
			"oidc.update",
			"saml.read",
			"saml.update",
			"webhook.read",
			"webhook.update",
			"webhook.replay",
			"post_auth_hook.read",
			"post_auth_hook.create",
			"post_auth_hook.update",
			"post_auth_hook.delete",
			"realtime.read",
			"realtime.update",
		},
		Metadata: map[string]any{
			"system":              true,
			"scope":               "tenant",
			"purpose":             "application_administration",
			"risk_level":          "high",
			"immutable_api_label": true,
		},
	},
	{
		APILabel:            "security_viewer",
		DisplayName:         "Security Viewer",
		Description:         "Read-only security, identity-policy, federation, session, device, key-metadata, and audit visibility.",
		Category:            "security",
		Assignable:          true,
		ProtectedFromDelete: true,
		PermissionLabels: []string{
			"tenant.read",
			"user.read",
			"role.read",
			"permission.read",
			"user_pool.read",
			"auth_policy.read",
			"password_policy.read",
			"recovery_policy.read",
			"login_policy.read",
			"session.read",
			"device.read",
			"mfa.read",
			"totp.read",
			"webauthn.read",
			"application.read",
			"oauth.read",
			"oidc.read",
			"saml.read",
			"webhook.read",
			"post_auth_hook.read",
			"key.read",
			"realtime.read",
			"audit.read",
		},
		Metadata: map[string]any{
			"system":              true,
			"scope":               "tenant",
			"purpose":             "security_observation",
			"risk_level":          "medium",
			"immutable_api_label": true,
			"read_only":           true,
		},
	},
	{
		APILabel:            "support_agent",
		DisplayName:         "Support Agent",
		Description:         "Supports tenant users with bounded session, device, and MFA recovery actions.",
		Category:            "support",
		Assignable:          true,
		ProtectedFromDelete: true,
		PermissionLabels: []string{
			"user.read",
			"session.read",
			"session.revoke",
			"device.read",
			"device.revoke",
			"mfa.read",
			"mfa.reset",
			"totp.read",
			"totp.reset",
			"webauthn.read",
			"webauthn.revoke",
			"recovery_policy.read",
			"support.read",
			"support.send",
		},
		Metadata: map[string]any{
			"system":              true,
			"scope":               "tenant",
			"purpose":             "user_support",
			"risk_level":          "high",
			"immutable_api_label": true,
		},
	},
	{
		APILabel:            "viewer",
		DisplayName:         "Viewer",
		Description:         "General read-only tenant administration visibility without cryptographic key metadata.",
		Category:            "read_only",
		Assignable:          true,
		ProtectedFromDelete: true,
		PermissionLabels: []string{
			"tenant.read",
			"user.read",
			"role.read",
			"permission.read",
			"user_pool.read",
			"auth_policy.read",
			"password_policy.read",
			"recovery_policy.read",
			"login_policy.read",
			"session.read",
			"device.read",
			"mfa.read",
			"totp.read",
			"webauthn.read",
			"application.read",
			"oauth.read",
			"oidc.read",
			"saml.read",
			"email.read",
			"sms.read",
			"notification.read",
			"webhook.read",
			"post_auth_hook.read",
			"realtime.read",
			"profile_field.read",
			"audit.read",
			"support.read",
		},
		Metadata: map[string]any{
			"system":              true,
			"scope":               "tenant",
			"purpose":             "read_only_administration",
			"risk_level":          "low",
			"immutable_api_label": true,
			"read_only":           true,
		},
	},
	{
		APILabel:            "standard_user",
		DisplayName:         "Standard User",
		Description:         "Self-service role for a normal tenant user.",
		Category:            "self_service",
		Assignable:          true,
		ProtectedFromDelete: true,
		PermissionLabels: []string{
			"self.profile.read",
			"self.profile.update",
			"self.session.read",
			"self.session.revoke",
			"self.device.read",
			"self.device.revoke",
			"self.mfa.manage",
		},
		Metadata: map[string]any{
			"system":              true,
			"scope":               "self",
			"purpose":             "end_user_self_service",
			"risk_level":          "low",
			"immutable_api_label": true,
		},
	},
}
