package constants

type PermissionDefinition struct {
	APILabel    string
	DisplayName string
	Description string
	Category    string
	Resource    string
	Action      string
	Scope       string
	RiskLevel   string
}

const DefaultPermissionCatalogVersion = "v1"

var DefaultPermissions = []PermissionDefinition{
	{
		APILabel:    "tenant.read",
		DisplayName: "Read Tenant",
		Description: "Read tenant configuration and lifecycle state.",
		Category:    "tenant",
		Resource:    "tenant",
		Action:      "read",
		Scope:       "tenant",
		RiskLevel:   "low",
	},
	{
		APILabel:    "tenant.update",
		DisplayName: "Update Tenant",
		Description: "Update tenant-owned configuration that is exposed to tenant administrators.",
		Category:    "tenant",
		Resource:    "tenant",
		Action:      "update",
		Scope:       "tenant",
		RiskLevel:   "high",
	},
	{
		APILabel:    "user.read",
		DisplayName: "Read Users",
		Description: "Read tenant administrative user records.",
		Category:    "identity",
		Resource:    "user",
		Action:      "read",
		Scope:       "tenant",
		RiskLevel:   "low",
	},
	{
		APILabel:    "user.create",
		DisplayName: "Create Users",
		Description: "Create tenant administrative or managed user records.",
		Category:    "identity",
		Resource:    "user",
		Action:      "create",
		Scope:       "tenant",
		RiskLevel:   "medium",
	},
	{
		APILabel:    "user.update",
		DisplayName: "Update Users",
		Description: "Update tenant user attributes.",
		Category:    "identity",
		Resource:    "user",
		Action:      "update",
		Scope:       "tenant",
		RiskLevel:   "medium",
	},
	{
		APILabel:    "user.disable",
		DisplayName: "Disable Users",
		Description: "Disable tenant user access.",
		Category:    "identity",
		Resource:    "user",
		Action:      "disable",
		Scope:       "tenant",
		RiskLevel:   "high",
	},
	{
		APILabel:    "user.block",
		DisplayName: "Block Users",
		Description: "Block tenant user authentication.",
		Category:    "identity",
		Resource:    "user",
		Action:      "block",
		Scope:       "tenant",
		RiskLevel:   "high",
	},
	{
		APILabel:    "user.delete",
		DisplayName: "Delete Users",
		Description: "Delete or soft-delete tenant user records.",
		Category:    "identity",
		Resource:    "user",
		Action:      "delete",
		Scope:       "tenant",
		RiskLevel:   "high",
	},
	{
		APILabel:    "user.invite",
		DisplayName: "Invite Users",
		Description: "Invite users into the tenant.",
		Category:    "identity",
		Resource:    "user",
		Action:      "invite",
		Scope:       "tenant",
		RiskLevel:   "medium",
	},
	{
		APILabel:    "role.read",
		DisplayName: "Read Roles",
		Description: "Read tenant role definitions and assignments.",
		Category:    "rbac",
		Resource:    "role",
		Action:      "read",
		Scope:       "tenant",
		RiskLevel:   "low",
	},
	{
		APILabel:    "role.create",
		DisplayName: "Create Roles",
		Description: "Create custom tenant roles.",
		Category:    "rbac",
		Resource:    "role",
		Action:      "create",
		Scope:       "tenant",
		RiskLevel:   "high",
	},
	{
		APILabel:    "role.update",
		DisplayName: "Update Roles",
		Description: "Update custom tenant role definitions.",
		Category:    "rbac",
		Resource:    "role",
		Action:      "update",
		Scope:       "tenant",
		RiskLevel:   "high",
	},
	{
		APILabel:    "role.delete",
		DisplayName: "Delete Roles",
		Description: "Delete eligible custom tenant roles.",
		Category:    "rbac",
		Resource:    "role",
		Action:      "delete",
		Scope:       "tenant",
		RiskLevel:   "high",
	},
	{
		APILabel:    "role.assign",
		DisplayName: "Assign Roles",
		Description: "Assign and remove tenant roles from members.",
		Category:    "rbac",
		Resource:    "role",
		Action:      "assign",
		Scope:       "tenant",
		RiskLevel:   "critical",
	},
	{
		APILabel:    "permission.read",
		DisplayName: "Read Permissions",
		Description: "Read the global permission catalog available to tenant roles.",
		Category:    "rbac",
		Resource:    "permission",
		Action:      "read",
		Scope:       "tenant",
		RiskLevel:   "low",
	},
	{
		APILabel:    "user_pool.read",
		DisplayName: "Read User Pools",
		Description: "Read tenant user pool configuration.",
		Category:    "identity",
		Resource:    "user_pool",
		Action:      "read",
		Scope:       "tenant",
		RiskLevel:   "low",
	},
	{
		APILabel:    "user_pool.create",
		DisplayName: "Create User Pools",
		Description: "Create tenant user pools.",
		Category:    "identity",
		Resource:    "user_pool",
		Action:      "create",
		Scope:       "tenant",
		RiskLevel:   "high",
	},
	{
		APILabel:    "user_pool.update",
		DisplayName: "Update User Pools",
		Description: "Update tenant user pool configuration.",
		Category:    "identity",
		Resource:    "user_pool",
		Action:      "update",
		Scope:       "tenant",
		RiskLevel:   "high",
	},
	{
		APILabel:    "user_pool.delete",
		DisplayName: "Delete User Pools",
		Description: "Delete eligible tenant user pools.",
		Category:    "identity",
		Resource:    "user_pool",
		Action:      "delete",
		Scope:       "tenant",
		RiskLevel:   "critical",
	},
	{
		APILabel:    "auth_policy.read",
		DisplayName: "Read Authentication Policy",
		Description: "Read tenant authentication policy.",
		Category:    "policy",
		Resource:    "auth_policy",
		Action:      "read",
		Scope:       "tenant",
		RiskLevel:   "low",
	},
	{
		APILabel:    "auth_policy.update",
		DisplayName: "Update Authentication Policy",
		Description: "Update tenant authentication policy.",
		Category:    "policy",
		Resource:    "auth_policy",
		Action:      "update",
		Scope:       "tenant",
		RiskLevel:   "critical",
	},
	{
		APILabel:    "password_policy.read",
		DisplayName: "Read Password Policy",
		Description: "Read tenant password policy.",
		Category:    "policy",
		Resource:    "password_policy",
		Action:      "read",
		Scope:       "tenant",
		RiskLevel:   "low",
	},
	{
		APILabel:    "password_policy.update",
		DisplayName: "Update Password Policy",
		Description: "Update tenant password policy.",
		Category:    "policy",
		Resource:    "password_policy",
		Action:      "update",
		Scope:       "tenant",
		RiskLevel:   "high",
	},
	{
		APILabel:    "recovery_policy.read",
		DisplayName: "Read Recovery Policy",
		Description: "Read tenant account recovery policy.",
		Category:    "policy",
		Resource:    "recovery_policy",
		Action:      "read",
		Scope:       "tenant",
		RiskLevel:   "low",
	},
	{
		APILabel:    "recovery_policy.update",
		DisplayName: "Update Recovery Policy",
		Description: "Update tenant account recovery policy.",
		Category:    "policy",
		Resource:    "recovery_policy",
		Action:      "update",
		Scope:       "tenant",
		RiskLevel:   "critical",
	},
	{
		APILabel:    "login_policy.read",
		DisplayName: "Read Login Policy",
		Description: "Read tenant login policy.",
		Category:    "policy",
		Resource:    "login_policy",
		Action:      "read",
		Scope:       "tenant",
		RiskLevel:   "low",
	},
	{
		APILabel:    "login_policy.update",
		DisplayName: "Update Login Policy",
		Description: "Update tenant login restrictions and behavior.",
		Category:    "policy",
		Resource:    "login_policy",
		Action:      "update",
		Scope:       "tenant",
		RiskLevel:   "high",
	},
	{
		APILabel:    "session.read",
		DisplayName: "Read Sessions",
		Description: "Read active tenant administrative sessions.",
		Category:    "security",
		Resource:    "session",
		Action:      "read",
		Scope:       "tenant",
		RiskLevel:   "medium",
	},
	{
		APILabel:    "session.revoke",
		DisplayName: "Revoke Sessions",
		Description: "Revoke tenant administrative sessions.",
		Category:    "security",
		Resource:    "session",
		Action:      "revoke",
		Scope:       "tenant",
		RiskLevel:   "high",
	},
	{
		APILabel:    "device.read",
		DisplayName: "Read Devices",
		Description: "Read registered or remembered devices.",
		Category:    "security",
		Resource:    "device",
		Action:      "read",
		Scope:       "tenant",
		RiskLevel:   "low",
	},
	{
		APILabel:    "device.revoke",
		DisplayName: "Revoke Devices",
		Description: "Revoke trusted or registered devices.",
		Category:    "security",
		Resource:    "device",
		Action:      "revoke",
		Scope:       "tenant",
		RiskLevel:   "high",
	},
	{
		APILabel:    "mfa.read",
		DisplayName: "Read MFA State",
		Description: "Read tenant member MFA enrollment state.",
		Category:    "security",
		Resource:    "mfa",
		Action:      "read",
		Scope:       "tenant",
		RiskLevel:   "medium",
	},
	{
		APILabel:    "mfa.reset",
		DisplayName: "Reset MFA",
		Description: "Reset tenant member MFA enrollment.",
		Category:    "security",
		Resource:    "mfa",
		Action:      "reset",
		Scope:       "tenant",
		RiskLevel:   "critical",
	},
	{
		APILabel:    "totp.read",
		DisplayName: "Read TOTP State",
		Description: "Read TOTP enrollment state.",
		Category:    "security",
		Resource:    "totp",
		Action:      "read",
		Scope:       "tenant",
		RiskLevel:   "medium",
	},
	{
		APILabel:    "totp.reset",
		DisplayName: "Reset TOTP",
		Description: "Reset a tenant member TOTP enrollment.",
		Category:    "security",
		Resource:    "totp",
		Action:      "reset",
		Scope:       "tenant",
		RiskLevel:   "critical",
	},
	{
		APILabel:    "webauthn.read",
		DisplayName: "Read Passkeys",
		Description: "Read WebAuthn/passkey enrollment metadata.",
		Category:    "security",
		Resource:    "webauthn",
		Action:      "read",
		Scope:       "tenant",
		RiskLevel:   "medium",
	},
	{
		APILabel:    "webauthn.revoke",
		DisplayName: "Revoke Passkeys",
		Description: "Revoke a tenant member passkey.",
		Category:    "security",
		Resource:    "webauthn",
		Action:      "revoke",
		Scope:       "tenant",
		RiskLevel:   "critical",
	},
	{
		APILabel:    "application.read",
		DisplayName: "Read Applications",
		Description: "Read tenant application clients.",
		Category:    "application",
		Resource:    "application",
		Action:      "read",
		Scope:       "tenant",
		RiskLevel:   "low",
	},
	{
		APILabel:    "application.create",
		DisplayName: "Create Applications",
		Description: "Create tenant application clients.",
		Category:    "application",
		Resource:    "application",
		Action:      "create",
		Scope:       "tenant",
		RiskLevel:   "high",
	},
	{
		APILabel:    "application.update",
		DisplayName: "Update Applications",
		Description: "Update tenant application clients.",
		Category:    "application",
		Resource:    "application",
		Action:      "update",
		Scope:       "tenant",
		RiskLevel:   "high",
	},
	{
		APILabel:    "application.disable",
		DisplayName: "Disable Applications",
		Description: "Disable tenant application clients.",
		Category:    "application",
		Resource:    "application",
		Action:      "disable",
		Scope:       "tenant",
		RiskLevel:   "high",
	},
	{
		APILabel:    "application.delete",
		DisplayName: "Delete Applications",
		Description: "Delete tenant application clients.",
		Category:    "application",
		Resource:    "application",
		Action:      "delete",
		Scope:       "tenant",
		RiskLevel:   "critical",
	},
	{
		APILabel:    "application.secret.rotate",
		DisplayName: "Rotate Application Secret",
		Description: "Rotate confidential application client secrets.",
		Category:    "application",
		Resource:    "application_secret",
		Action:      "rotate",
		Scope:       "tenant",
		RiskLevel:   "critical",
	},
	{
		APILabel:    "oauth.read",
		DisplayName: "Read OAuth Configuration",
		Description: "Read tenant OAuth grants and configuration.",
		Category:    "federation",
		Resource:    "oauth",
		Action:      "read",
		Scope:       "tenant",
		RiskLevel:   "medium",
	},
	{
		APILabel:    "oauth.revoke",
		DisplayName: "Revoke OAuth Grants",
		Description: "Revoke tenant OAuth grants.",
		Category:    "federation",
		Resource:    "oauth",
		Action:      "revoke",
		Scope:       "tenant",
		RiskLevel:   "high",
	},
	{
		APILabel:    "oidc.read",
		DisplayName: "Read OIDC Configuration",
		Description: "Read tenant OIDC configuration.",
		Category:    "federation",
		Resource:    "oidc",
		Action:      "read",
		Scope:       "tenant",
		RiskLevel:   "low",
	},
	{
		APILabel:    "oidc.update",
		DisplayName: "Update OIDC Configuration",
		Description: "Update tenant OIDC configuration.",
		Category:    "federation",
		Resource:    "oidc",
		Action:      "update",
		Scope:       "tenant",
		RiskLevel:   "high",
	},
	{
		APILabel:    "saml.read",
		DisplayName: "Read SAML Configuration",
		Description: "Read tenant SAML configuration.",
		Category:    "federation",
		Resource:    "saml",
		Action:      "read",
		Scope:       "tenant",
		RiskLevel:   "low",
	},
	{
		APILabel:    "saml.update",
		DisplayName: "Update SAML Configuration",
		Description: "Update tenant SAML configuration.",
		Category:    "federation",
		Resource:    "saml",
		Action:      "update",
		Scope:       "tenant",
		RiskLevel:   "high",
	},
	{
		APILabel:    "email.read",
		DisplayName: "Read Email Configuration",
		Description: "Read tenant email provider and template configuration.",
		Category:    "communications",
		Resource:    "email",
		Action:      "read",
		Scope:       "tenant",
		RiskLevel:   "low",
	},
	{
		APILabel:    "email.update",
		DisplayName: "Update Email Configuration",
		Description: "Update tenant email provider and template configuration.",
		Category:    "communications",
		Resource:    "email",
		Action:      "update",
		Scope:       "tenant",
		RiskLevel:   "high",
	},
	{
		APILabel:    "sms.read",
		DisplayName: "Read SMS Configuration",
		Description: "Read tenant SMS provider configuration.",
		Category:    "communications",
		Resource:    "sms",
		Action:      "read",
		Scope:       "tenant",
		RiskLevel:   "low",
	},
	{
		APILabel:    "sms.update",
		DisplayName: "Update SMS Configuration",
		Description: "Update tenant SMS provider configuration.",
		Category:    "communications",
		Resource:    "sms",
		Action:      "update",
		Scope:       "tenant",
		RiskLevel:   "high",
	},
	{
		APILabel:    "notification.read",
		DisplayName: "Read Notification Configuration",
		Description: "Read tenant notification configuration.",
		Category:    "communications",
		Resource:    "notification",
		Action:      "read",
		Scope:       "tenant",
		RiskLevel:   "low",
	},
	{
		APILabel:    "notification.update",
		DisplayName: "Update Notification Configuration",
		Description: "Update tenant notification configuration.",
		Category:    "communications",
		Resource:    "notification",
		Action:      "update",
		Scope:       "tenant",
		RiskLevel:   "medium",
	},
	{
		APILabel:    "webhook.read",
		DisplayName: "Read Webhooks",
		Description: "Read tenant webhook configuration and delivery metadata.",
		Category:    "integration",
		Resource:    "webhook",
		Action:      "read",
		Scope:       "tenant",
		RiskLevel:   "low",
	},
	{
		APILabel:    "webhook.update",
		DisplayName: "Update Webhooks",
		Description: "Create or update tenant webhooks.",
		Category:    "integration",
		Resource:    "webhook",
		Action:      "update",
		Scope:       "tenant",
		RiskLevel:   "high",
	},
	{
		APILabel:    "webhook.replay",
		DisplayName: "Replay Webhooks",
		Description: "Replay eligible tenant webhook deliveries.",
		Category:    "integration",
		Resource:    "webhook",
		Action:      "replay",
		Scope:       "tenant",
		RiskLevel:   "high",
	},
	{
		APILabel:    "post_auth_hook.read",
		DisplayName: "Read Post-auth Hooks",
		Description: "Read post-authentication hook configuration.",
		Category:    "integration",
		Resource:    "post_auth_hook",
		Action:      "read",
		Scope:       "tenant",
		RiskLevel:   "low",
	},
	{
		APILabel:    "post_auth_hook.create",
		DisplayName: "Create Post-auth Hooks",
		Description: "Create post-authentication hooks.",
		Category:    "integration",
		Resource:    "post_auth_hook",
		Action:      "create",
		Scope:       "tenant",
		RiskLevel:   "high",
	},
	{
		APILabel:    "post_auth_hook.update",
		DisplayName: "Update Post-auth Hooks",
		Description: "Update post-authentication hooks.",
		Category:    "integration",
		Resource:    "post_auth_hook",
		Action:      "update",
		Scope:       "tenant",
		RiskLevel:   "high",
	},
	{
		APILabel:    "post_auth_hook.delete",
		DisplayName: "Delete Post-auth Hooks",
		Description: "Delete post-authentication hooks.",
		Category:    "integration",
		Resource:    "post_auth_hook",
		Action:      "delete",
		Scope:       "tenant",
		RiskLevel:   "high",
	},
	{
		APILabel:    "key.read",
		DisplayName: "Read Key Metadata",
		Description: "Read tenant cryptographic key metadata without exposing key material.",
		Category:    "security",
		Resource:    "key",
		Action:      "read",
		Scope:       "tenant",
		RiskLevel:   "medium",
	},
	{
		APILabel:    "key.rotate",
		DisplayName: "Rotate Tenant Keys",
		Description: "Rotate tenant-scoped cryptographic keys.",
		Category:    "security",
		Resource:    "key",
		Action:      "rotate",
		Scope:       "tenant",
		RiskLevel:   "critical",
	},
	{
		APILabel:    "realtime.read",
		DisplayName: "Read Realtime Configuration",
		Description: "Read tenant realtime configuration.",
		Category:    "integration",
		Resource:    "realtime",
		Action:      "read",
		Scope:       "tenant",
		RiskLevel:   "low",
	},
	{
		APILabel:    "realtime.update",
		DisplayName: "Update Realtime Configuration",
		Description: "Update tenant realtime configuration.",
		Category:    "integration",
		Resource:    "realtime",
		Action:      "update",
		Scope:       "tenant",
		RiskLevel:   "high",
	},
	{
		APILabel:    "profile_field.read",
		DisplayName: "Read Profile Field Definitions",
		Description: "Read tenant profile field definitions.",
		Category:    "identity",
		Resource:    "profile_field",
		Action:      "read",
		Scope:       "tenant",
		RiskLevel:   "low",
	},
	{
		APILabel:    "profile_field.create",
		DisplayName: "Create Profile Field Definitions",
		Description: "Create tenant profile field definitions.",
		Category:    "identity",
		Resource:    "profile_field",
		Action:      "create",
		Scope:       "tenant",
		RiskLevel:   "medium",
	},
	{
		APILabel:    "profile_field.update",
		DisplayName: "Update Profile Field Definitions",
		Description: "Update tenant profile field definitions.",
		Category:    "identity",
		Resource:    "profile_field",
		Action:      "update",
		Scope:       "tenant",
		RiskLevel:   "medium",
	},
	{
		APILabel:    "profile_field.delete",
		DisplayName: "Delete Profile Field Definitions",
		Description: "Delete tenant profile field definitions.",
		Category:    "identity",
		Resource:    "profile_field",
		Action:      "delete",
		Scope:       "tenant",
		RiskLevel:   "high",
	},
	{
		APILabel:    "audit.read",
		DisplayName: "Read Audit Events",
		Description: "Read tenant-visible audit events.",
		Category:    "audit",
		Resource:    "audit",
		Action:      "read",
		Scope:       "tenant",
		RiskLevel:   "medium",
	},
	{
		APILabel:    "support.read",
		DisplayName: "Read Support Data",
		Description: "Read tenant support data and cases.",
		Category:    "support",
		Resource:    "support",
		Action:      "read",
		Scope:       "tenant",
		RiskLevel:   "medium",
	},
	{
		APILabel:    "support.send",
		DisplayName: "Perform Support Actions",
		Description: "Perform permitted tenant support actions.",
		Category:    "support",
		Resource:    "support",
		Action:      "send",
		Scope:       "tenant",
		RiskLevel:   "high",
	},
	{
		APILabel:    "self.profile.read",
		DisplayName: "Read Own Profile",
		Description: "Read the authenticated user own profile.",
		Category:    "self_service",
		Resource:    "self_profile",
		Action:      "read",
		Scope:       "self",
		RiskLevel:   "low",
	},
	{
		APILabel:    "self.profile.update",
		DisplayName: "Update Own Profile",
		Description: "Update allowed fields on the authenticated user own profile.",
		Category:    "self_service",
		Resource:    "self_profile",
		Action:      "update",
		Scope:       "self",
		RiskLevel:   "low",
	},
	{
		APILabel:    "self.session.read",
		DisplayName: "Read Own Sessions",
		Description: "Read the authenticated user own sessions.",
		Category:    "self_service",
		Resource:    "self_session",
		Action:      "read",
		Scope:       "self",
		RiskLevel:   "low",
	},
	{
		APILabel:    "self.session.revoke",
		DisplayName: "Revoke Own Sessions",
		Description: "Revoke the authenticated user own sessions.",
		Category:    "self_service",
		Resource:    "self_session",
		Action:      "revoke",
		Scope:       "self",
		RiskLevel:   "low",
	},
	{
		APILabel:    "self.device.read",
		DisplayName: "Read Own Devices",
		Description: "Read the authenticated user own devices.",
		Category:    "self_service",
		Resource:    "self_device",
		Action:      "read",
		Scope:       "self",
		RiskLevel:   "low",
	},
	{
		APILabel:    "self.device.revoke",
		DisplayName: "Revoke Own Devices",
		Description: "Revoke the authenticated user own devices.",
		Category:    "self_service",
		Resource:    "self_device",
		Action:      "revoke",
		Scope:       "self",
		RiskLevel:   "low",
	},
	{
		APILabel:    "self.mfa.manage",
		DisplayName: "Manage Own MFA",
		Description: "Enroll, update, or remove the authenticated user own MFA methods subject to policy.",
		Category:    "self_service",
		Resource:    "self_mfa",
		Action:      "manage",
		Scope:       "self",
		RiskLevel:   "medium",
	},
}
